# https://git.sc.uni-leipzig.de/miku/span/-/ci/lint

# The first thing is to choose what Docker image will be used to run the CI.
# Head to the Docker Hub to choose the right image for your project.
image: golang:1.11.3

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

before_script:
  - mkdir -p /go/src/github.com/miku /go/src/_/builds
  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/miku/span
  - ln -s /go/src/github.com/miku /go/src/_/builds/miku
  - make deps

stages:
  - test

unit_tests:
  stage: test
  script:
    - make test

